name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Debug

jobs:
  build-osx:
    runs-on: [self-hosted, macos]
    if: ${{ !contains(github.event.head_commit.message, 'skip-ci') && !contains(github.event.head_commit.message, 'skip-mac')}}
    env:
      VCPKG_ROOT: /Users/schwarzer/vcpkg
      REPO_ROOT: /Users/schwarzer/blive-face-relay
      HTTP_PROXY: 'socks5://127.0.0.1:10808'
      HTTPS_PROXY: 'socks5://127.0.0.1:10808'

    steps:
      - name: Install cmake
        uses: lukka/get-cmake@latest
        with:
          useCloudCache: false
          useLocalCache: true

      - name: Update vcpkg
        working-directory: /Users/schwarzer/vcpkg
        run: git fetch reito reito && git reset --hard reito/reito

      - name: Update relay
        working-directory: ${{env.REPO_ROOT}}
        run: git fetch origin main && git reset --hard origin/main

      - name: Configure CMake X86_64
        working-directory: ${{env.REPO_ROOT}}
        run: cmake -G Ninja -B ${{env.REPO_ROOT}}/out/build-x64 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DVCPKG_TARGET_TRIPLET=x64-osx -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.REPO_ROOT}}/out/install-x64

      - name: Build X86_64
        working-directory: ${{env.REPO_ROOT}}
        run: cmake --build ${{env.REPO_ROOT}}/out/build-x64 --target FaceRelay -j $NUMBER_OF_PROCESSORS

      - name: Install X86_64
        working-directory: ${{env.REPO_ROOT}}
        run: cmake --build ${{env.REPO_ROOT}}/out/build-x64 --config ${{env.BUILD_TYPE}} --target install -j $NUMBER_OF_PROCESSORS

      - name: Configure CMake ARM64
        working-directory: ${{env.REPO_ROOT}}
        run: cmake -G Ninja -B ${{env.REPO_ROOT}}/out/build-arm64 -DCMAKE_OSX_ARCHITECTURES=arm64 -DVCPKG_TARGET_TRIPLET=arm64-osx -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.REPO_ROOT}}/out/install-arm64

      - name: Build ARM64
        working-directory: ${{env.REPO_ROOT}}
        run: cmake --build ${{env.REPO_ROOT}}/out/build-arm64 --target FaceRelay -j $NUMBER_OF_PROCESSORS

      - name: Install ARM64
        working-directory: ${{env.REPO_ROOT}}
        run: cmake --build ${{env.REPO_ROOT}}/out/build-arm64 --config ${{env.BUILD_TYPE}} --target install -j $NUMBER_OF_PROCESSORS

      - name: Merge Binary
        shell: bash
        run: |
          mkdir -p ${{env.REPO_ROOT}}/out/install/bin
          lipo -create -output ${{env.REPO_ROOT}}/out/install/bin/FaceRelay \
              ${{env.REPO_ROOT}}/out/install-arm64/bin/FaceRelay \
              ${{env.REPO_ROOT}}/out/install-x64/bin/FaceRelay

      - name: Get Updator
        uses: actions/checkout@v3
        with:
          repository: 'cnSchwarzer/Updator'
          path: '${{github.workspace}}/updator'

      - name: Get Updator config
        uses: actions/checkout@v3
        with:
          repository: 'reitovo/ci-private'
          path: '${{github.workspace}}/ci'
          token: ${{ secrets.CI_PRIVATE_TOKEN }}
          ref: 'ci'

      - name: Build Updator uploader
        working-directory: '${{github.workspace}}/updator/Updator.Uploader'
        run: 'dotnet build -o ${{github.workspace}}/uploader'

      - name: Publish build
        shell: bash
        run: |
          dotnet ${{github.workspace}}/uploader/Updator.Uploader.dll \
          --config=${{github.workspace}}/ci/blive-face-relay/osx.json \
          --distribution-root=${{env.REPO_ROOT}}/out/install \
          --update-log="Commit ${{github.event.head_commit.message}}"

  build-win:
    runs-on: [self-hosted, windows]
    if: ${{ !contains(github.event.head_commit.message, 'skip-ci') && !contains(github.event.head_commit.message, 'skip-win') }}
    env:
      REPO_ROOT: C:/blive-face-relay

    steps:
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Update vcpkg
        working-directory: C:/vcpkg
        run: git fetch reito reito && git reset --hard reito/reito

      - name: Update relay
        working-directory: ${{env.REPO_ROOT}}
        run: git fetch origin main && git reset --hard origin/main

      - name: Configure CMake
        working-directory: ${{env.REPO_ROOT}}
        run: cmake -G Ninja -B ${{env.REPO_ROOT}}/out/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.REPO_ROOT}}/out/install

      - name: Build
        working-directory: ${{env.REPO_ROOT}}
        run: cmake --build ${{env.REPO_ROOT}}/out/build --target FaceRelay -j $NUMBER_OF_PROCESSORS

      - name: Install
        working-directory: ${{env.REPO_ROOT}}
        run: cmake --build ${{env.REPO_ROOT}}/out/build --config ${{env.BUILD_TYPE}} --target install -j $NUMBER_OF_PROCESSORS

      - name: Get Updator
        uses: actions/checkout@v3
        with:
          repository: 'cnSchwarzer/Updator'
          path: '${{github.workspace}}/updator'

      - name: Get Updator config
        uses: actions/checkout@v3
        with:
          repository: 'reitovo/ci-private'
          path: '${{github.workspace}}/ci'
          token: ${{ secrets.CI_PRIVATE_TOKEN }}
          ref: 'ci'

      - name: Build Updator uploader
        working-directory: '${{github.workspace}}/updator/Updator.Uploader'
        run: 'dotnet build -o ${{github.workspace}}/uploader'

      - name: Publish build
        shell: pwsh
        run: |
          dotnet ${{github.workspace}}/uploader/Updator.Uploader.dll `
          --config=${{github.workspace}}/ci/blive-face-relay/win.json `
          --distribution-root=${{env.REPO_ROOT}}/out/install `
          --update-log="Commit ${{github.event.head_commit.message}}"